version: 2.1
jobs:

  lint-and-build:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true

    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: ./.circleci/install-yarn.sh
      - restore_cache:
          keys:
          - v3-deps-{{ checksum "package.json" }}
          - v3-deps-
      - run: source /opt/circleci/.nvm/nvm.sh && yarn --production
      - run: source /opt/circleci/.nvm/nvm.sh && yarn lint
      - run: source /opt/circleci/.nvm/nvm.sh && yarn build
      - save_cache:
          paths:
            - node_modules
          key: v3-deps-{{ checksum "package.json" }}

  test-container:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true

    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: make test-container

  tests:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true

    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: ./.circleci/install-yarn.sh
      - restore_cache:
          keys:
          - v3-deps-{{ checksum "package.json" }}
          - v3-deps-
      - run: source /opt/circleci/.nvm/nvm.sh && yarn --production
      - run: source /opt/circleci/.nvm/nvm.sh && make tests
      - save_cache:
          paths:
            - node_modules
          key: v3-deps-{{ checksum "package.json" }}

workflows:
  version: 2

  mainflow:
    jobs:
      - lint-and-build
      - test-container
      - tests

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint-and-build
      - test-container
      - tests
